# Generated by Django 2.2 on 2021-04-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStudentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter nickname', max_length=30, unique=True, verbose_name='nickname')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=60, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='date registration')),
                ('location', models.CharField(blank=True, help_text='add Country', max_length=30, verbose_name='Location')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_mentor', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='useraccounts.SiteUser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter group name', max_length=50, verbose_name='Students group')),
                ('entry_date', models.DateField(verbose_name='Entry date')),
                ('graduation_date', models.DateField(verbose_name='Graduation date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(through='useraccounts.GroupStudentRelation', to='useraccounts.StudentsGroup')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='useraccounts.SiteUser')),
            ],
        ),
        migrations.AddField(
            model_name='groupstudentrelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='useraccounts.StudentsGroup'),
        ),
        migrations.AddField(
            model_name='groupstudentrelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='useraccounts.Student'),
        ),
    ]
