# Generated by Django 2.2 on 2021-03-22 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='add event description', max_length=100, verbose_name='event details')),
                ('start_at', models.DateTimeField(verbose_name='Start date')),
                ('end_till', models.DateTimeField(verbose_name='End till')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='useraccounts.StudentsGroup')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='useraccounts.Trainer')),
            ],
            options={
                'ordering': ['start_at', 'end_till'],
            },
        ),
    ]
